# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_ansible
from pulpcore.client.pulp_ansible.api.content_namespaces_api import ContentNamespacesApi  # noqa: E501
from pulpcore.client.pulp_ansible.rest import ApiException


class TestContentNamespacesApi(unittest.TestCase):
    """ContentNamespacesApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_ansible.api.content_namespaces_api.ContentNamespacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_avatar(self):
        """Test case for avatar

        """
        pass

    def test_list(self):
        """Test case for list

        List ansible namespace metadatas  # noqa: E501
        """
        pass

    def test_read(self):
        """Test case for read

        Inspect an ansible namespace metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
