
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-06T17:47:56+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "76d9b0b752e5e453e3046d5864750c4e3ad85b36",
 "version": "1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
