# coding: utf-8

"""
    Obhenie s pokupatelami

    <div class=\"description_important\">       Uznat bolhe ob obhenii s pokupatelami mohno v <a href=\"https://seller.wildberries.ru/instructions/category/f7f6c465-dd12-422d-80a0-a6d9562115d5?goBackOption=prevRoute&categoryId=30817062-14cc-4a82-bc78-3600c2b0685b\">spravohnom centre</a> </div>  herez metody obhenia s pokupatelem vy mohete rabotat s:   1. [Voprosami](/openapi/user-communication#tag/Voprosy) i [otzyvami](/openapi/user-communication#tag/Otzyvy) pokupatelei   2. [hablonami otvetov](/openapi/user-communication#tag/Shablony-otvetov) na voprosy i otzyvy   3. [hatami s pokupatelami](/openapi/user-communication#tag/Chat-s-pokupatelyami)   4. [Zaavkami pokupatelei na vozvrat](/openapi/user-communication#tag/Vozvraty-pokupatelyami)   # noqa: E501

    OpenAPI spec version: communication
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SellerMessageBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reply_sign': 'str',
        'message': 'str',
        'file': 'list[str]'
    }

    attribute_map = {
        'reply_sign': 'replySign',
        'message': 'message',
        'file': 'file'
    }

    def __init__(self, reply_sign=None, message=None, file=None):  # noqa: E501
        """SellerMessageBody - a model defined in Swagger"""  # noqa: E501
        self._reply_sign = None
        self._message = None
        self._file = None
        self.discriminator = None
        self.reply_sign = reply_sign
        if message is not None:
            self.message = message
        if file is not None:
            self.file = file

    @property
    def reply_sign(self):
        """Gets the reply_sign of this SellerMessageBody.  # noqa: E501

        Podpis hata. Mohno poluhit iz [informacii po hatu](./user-communication#tag/Chat-s-pokupatelyami/paths/~1api~1v1~1seller~1chats/get) ili [dannyh sobytia](./user-communication#tag/Chat-s-pokupatelyami/paths/~1api~1v1~1seller~1events/get), esli v sobytii est pole `\"isNewChat\": true`.   # noqa: E501

        :return: The reply_sign of this SellerMessageBody.  # noqa: E501
        :rtype: str
        """
        return self._reply_sign

    @reply_sign.setter
    def reply_sign(self, reply_sign):
        """Sets the reply_sign of this SellerMessageBody.

        Podpis hata. Mohno poluhit iz [informacii po hatu](./user-communication#tag/Chat-s-pokupatelyami/paths/~1api~1v1~1seller~1chats/get) ili [dannyh sobytia](./user-communication#tag/Chat-s-pokupatelyami/paths/~1api~1v1~1seller~1events/get), esli v sobytii est pole `\"isNewChat\": true`.   # noqa: E501

        :param reply_sign: The reply_sign of this SellerMessageBody.  # noqa: E501
        :type: str
        """
        if reply_sign is None:
            raise ValueError("Invalid value for `reply_sign`, must not be `None`")  # noqa: E501

        self._reply_sign = reply_sign

    @property
    def message(self):
        """Gets the message of this SellerMessageBody.  # noqa: E501

        Tekst soobhenia. Maksimum 1000 simvolov.  # noqa: E501

        :return: The message of this SellerMessageBody.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this SellerMessageBody.

        Tekst soobhenia. Maksimum 1000 simvolov.  # noqa: E501

        :param message: The message of this SellerMessageBody.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def file(self):
        """Gets the file of this SellerMessageBody.  # noqa: E501

        Faily, format JPEG, PDF ili PNG, maksimalnyi razmer — 5 Mb kahdyi. Maksimalnyi summarnyi razmer failov — 30 Mb.   # noqa: E501

        :return: The file of this SellerMessageBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this SellerMessageBody.

        Faily, format JPEG, PDF ili PNG, maksimalnyi razmer — 5 Mb kahdyi. Maksimalnyi summarnyi razmer failov — 30 Mb.   # noqa: E501

        :param file: The file of this SellerMessageBody.  # noqa: E501
        :type: list[str]
        """

        self._file = file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SellerMessageBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SellerMessageBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
