from .recorder import MeshcatRecorder as MeshcatRecorder
from .server import start_meshcat_server as start_meshcat_server
from .utilities import interactive_mode as interactive_mode
from _typeshed import Incomplete
from comm import BaseComm as BaseComm
from ipykernel.ipkernel import IPythonKernel as IPythonKernel

SHELL_PRIORITY: int
IPYKERNEL_VERSION_MAJOR: Incomplete

class CommProcessor:
    qsize_old: int
    is_running: bool
    def __init__(self) -> None: ...
    def __call__(self) -> None: ...

process_kernel_comm: Incomplete

class CommManager:
    def __init__(self, comm_url: str) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...

class MeshcatWrapper:
    gui: Incomplete
    recorder: Incomplete
    comm_manager: CommManager | None
    def __init__(self, zmq_url: str | None = None, comm_url: str | None = None) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...
    def wait(self, require_client: bool = False) -> str: ...
    def set_legend_item(self, uniq_id: str, color: str, text: str) -> None: ...
    def remove_legend_item(self, uniq_id: str) -> None: ...
    def set_watermark(self, img_fullpath: str, width: int, height: int) -> None: ...
    def remove_watermark(self) -> None: ...
    def start_recording(self, fps: float, width: int, height: int) -> None: ...
    def stop_recording(self, path: str) -> None: ...
    def add_frame(self) -> None: ...
    def capture_frame(self, width: int | None = None, height: int | None = None) -> str: ...
