aus_names_dic = {
    '1,3-Benzodioxolylbutanamine (BDB)': '1,3-Benzodioxolylbutanamine',
    '4-[(6E)-3-Hydroxy-8,10-dimethyl-2-(methylamino)-6-dodecen-1-yl]phenol':
        '4-[(E)-3-Hydroxy-8,10-dimethyl-2-(methylamino)dodec-6-enyl]phenol',
    'Acetyl-_-methylcholine': 'Acetyl-beta-methylthiocholine',
    'Bis(4-ethylbenzylidene)sorbitol': 'Di-(p-ethylbenzylidene)sorbitol',
    'CP 24,879': '4-(3-Methylbutoxy)aniline',
    'DL-_-Aminocaprylic acid': '2-Aminooctanoic acid',
    'Hexamethoxymethyl melamine': 'Hexa(methoxymethyl)melamine',
    'Kanosamine': '3-Amino-3-deoxyglucose',
    'Methyl (2R)-[(1S,3S,7R,8R,12S,13S)-13-(3-furyl)-6,6,8,12-tetramethyl-17-methylene-5,15-dioxo-'
    '2,14-dioxatetracyclo[7.7.1.01,12 03,8]heptadec-7-yl](hydroxy)acetate': '6-Hydroxyangolensic acid methyl ester',
    "N-(tert-Butyl)-N'-(2-hydroxyethyl)urea": '1-(2-Hydroxyethyl)-3-t-butylurea',
    'N-Methyl-2-AI': 'N-methyl-2,3-dihydro-1H-inden-2-amine',  # modified June 13
    'Nikethamide 1-oxide': 'N,N-Diethylnicotinamide 1-oxide',
    'Oxepanone': 'Caprolactone',
    'PEG n10': '3,6,9,12,15,18,21,24,27-Nonaoxanonacosane-1,29-diol',
    'PEG n11': '3,6,9,12,15,18,21,24,27,30-Decaoxadotriacontane-1,32-diol',
    'PEG n12': 'Dodecaethylene glycol',
    'PEG n13': '3,6,9,12,15,18,21,24,27,30,33,36-Dodecaoxaoctatriacontane-1,38-diol',
    'PEG n14': '3,6,9,12,15,18,21,24,27,30,33,36,39-Tridecaoxahentetracontane-1,41-diol',
    'PEG n15': '3,6,9,12,15,18,21,24,27,30,33,36,39,42-Tetradecaoxatetratetracontane-1,44-diol',
    'PEG n16': '3,6,9,12,15,18,21,24,27,30,33,36,39,42,45-Pentadecaoxaheptatetracontane-1,47-diol',
    'PEG n5': 'Pentaethylene glycol',
    'PEG n6': 'Hexaethylene glycol',
    'PEG n7': '3,6,9,12,15,18-Hexaoxaicosane-1,20-diol',
    'PEG n8': '3,6,9,12,15,18,21-Heptaoxatricosane-1,23-diol',
    'PPG n11': 'Undecapropylene glycol',
    'PPG n5': 'Pentapropylene glycol',
    'PPG n6': 'Hexapropylene glycol',
    'PPG n7': 'Heptapropylene glycol',
    'PPG n8': 'Octapropylene glycol',
    'PPG n9': 'Nonapropylene glycol',
    '_-Aspartylphenylalanine': 'L-Aspartyl-L-phenylalanine',
    '_-Eleostearic acid': 'alpha-Eleostearic acid',
    '_-Linolenic acid': 'Linolenic Acid ',
    '_-Valerolactam': '2-Piperidone',
    '1-(4-Chlorobenzyl)-4,6-dimethyl-2-oxo-1,2-dihydropyridine-3-carbonitrile':
        '1-[(4-Chlorophenyl)methyl]-1,2-dihydro-4,6-dimethyl-2-oxo-3-pyridinecarbonitrile',
    '2-Methyl-4-chlorophenoxyacetic acid (MCPA)': '(4-Chloro-2-methylphenoxy)acetic acid',
    '2,6-Bis[(2-hydroxyethyl)amino]-3-nitrobenzonitrile': '2,6-Bis(2-hydroxyethylamino)-3-nitrobenzonitrile',
    '3-(2,1,3-Benzothiadiazol-4-ylamino)-2-(2,2-dimethylpropanoyl)acrylonitrile':
        'QZOMZISEDDJTHO-CMDGGOBGSA-N',
    "4,4'-Dihydroxydiphenylsulfone": "4,4'-Sulfonyldiphenol",
    'D-(+)-Galactose': 'D-Galactose',
    'Ibuprofen metabolite B': 'Carboxyibuprofen',
    'Mono(2-ethylhexyl) phthalate (MEHP)': '2-(((2-Ethylhexyl)oxy)carbonyl)benzoic acid',
    '(-)-Corey lactone': 'VYTZWRCSPHQSFX-GBNDHIKLSA-N',
    '_-Lactose': 'alpha-Lactose',
    '_-Gluconic acid _-lactone': 'Gluconolactone',
    'D-(+)-Xylose': 'D-Xylose',
    'Corchorifatty acid F': '(10e,15z)-9,12,13-Trihydroxyoctadeca-10,15-dienoic acid'
}

amar_names_dic = {
    '1-(4-Methoxyphenyl)-N-({(2R,4S,5R)-5-[1-methyl-3-(2-thienyl)-1H-pyrazol-5-yl]-1-azabicyclo[2.2.2]oct-2-yl}methyl)'
    'methanamine': 'PQIBHGTXCNLNFG-ZVDOUQERSA-N',
    '1-[4-hydroxy-5-(hydroxymethyl)tetrahydrofuran-2-yl]pyrimidine-2,4(1H,3H)-dione':
        '1-((2R,4R,5S)-4-Hydroxy-5-(hydroxymethyl)tetrahydrofuran-2-yl)pyrimidine-2,4(1H,3H)-dione',
    '1-Methoxy-3-carbaldehyde': '1-Methoxyindole-3-carbaldehyde',
    '2-(4-chlorobenzoyl)-3-[(3-oxo-1,3-dihydroisobenzofuran-5-yl)amino]acrylonitrile': 'BAXLYEAEVMOZSJ-UKTHLTGXSA-N',
    '2,3-dimethylbenzene sulfonic acid': '2,3-Dimethylbenzenesulfonic acid',
    '2-[(2S,4aR,8aS)-2-Hydroxy-4a-methyl-8-methylenedecahydro-2-naphthalenyl]acrylic acid':
        '2-[(2S,4aR,8aS)-2-hydroxy-4a-methyl-8-methylidene-3,4,5,6,7,8a-hexahydro-1H-naphthalen-2-yl]prop-2-enoic acid',
    '2-{[Carboxy(phenyl)methyl]amino}benzoic acid': '2-(alpha-Carboxybenzylamino)benzoic acid',
    '3-[5-(benzylthio)-4-methyl-4H-1,2,4-triazol-3-yl]-5-oct-1-ynylpyridine': 'AQWTXPJMHNDSQP-UHFFFAOYSA-N',
    '4- Carboxyphenylglycine': '4-Carboxyphenylglycine',
    "4'-Chloro-α-pyrrolidinopropiophenone": '4-Chloro-alpha-pvp',
    'Azelaic acid (Not validated)': 'Azelaic acid',
    'Acetylleucine (isomer of 164)': 'Acetylleucine',
    'C12 AEO-2': 'AZLWQVJVINEILY-UHFFFAOYSA-N',
    'C12 AEO-3': 'FKMHSNTVILORFA-UHFFFAOYSA-N',
    'C12 AEO-4': 'WPMWEFXCIYCJSA-UHFFFAOYSA-N',
    'C12 AEO-5': 'LAPRIVJANDLWOK-UHFFFAOYSA-N',
    'C12 AEO-6': 'OJCFEGKCRWEVSN-UHFFFAOYSA-N',
    'C12 AEO-7': 'DWHIUNMOTRUVPG-UHFFFAOYSA-N',
    'C12 AEO-8': 'YYELLDKEOUKVIQ-UHFFFAOYSA-N',
    'C12 AEO-9': 'ONJQDTZCDSESIW-UHFFFAOYSA-N',
    'Citric acid (Not validated, isomer of 227)': 'KRKNYBCHXYNGOX-UHFFFAOYSA-N',
    'Coumarin base + 1O, 1MeO': ' RODXRVNMMDRFIK-UHFFFAOYSA-N',
    'Cyclo(phenylalanyl-prolyl)': 'Pyrrolo[1,2-a]pyrazine-1,4-dione, hexahydro-3-(phenylmethyl)-',
    'DL-α-Aminocaprylic acid': '2-Aminooctanoic acid',
    'Ethyl 4-(2-thioxo-2,3-dihydro-1H-benzimidazol-1-yl)benzoate':
        'LKLKMJUQNDXMTH-UHFFFAOYSA-N',
    'Glutamylphenylalanine (isomer of 1503)': 'XHHOHZPNYFQJKL-UHFFFAOYSA-N',
    'Hydroxysuberic acid': 'ARJZZFJXSNJKGR-UHFFFAOYSA-N',
    'Imino(methyl)phenyl-lambda~4~-sulfane 2,4,6-trimethylbenzenesulfonic acid': '2,4,6-Trimethylbenzenesulfonic acid',
    'Methoxytyrosine': '3-Methoxytyrosine',
    'N-Methyl-2-AI': 'N-methyl-2,3-dihydro-1H-inden-2-amine',
    'NP-003319': 'GXYLOXCSJFJFKA-UHFFFAOYSA-N',
    'NP-011220': 'ZDACRNZBFJOLTC-UHFFFAOYSA-N',
    'NP-013736': 'XLUAWXQORJEMBD-UHFFFAOYSA-N',
    'NP-016455': 'CSRXCVLPMJBQIM-UHFFFAOYSA-N',
    'NP-016564': 'UGHXSOJROIYABR-UHFFFAOYSA-N',
    'NP1EC (TENTATIVE)': 'NISAHDHKGPWBEM-UHFFFAOYSA-N',
    'N-Phenylacetylglutamine': 'Phenylacetylglutamine',
    'PEG n5': 'Pentaethylene glycol',
    'PEG-10EO': '3,6,9,12,15,18,21,24,27-Nonaoxanonacosane-1,29-diol',
    'PEG-6EO': 'Hexaethylene glycol',
    'PEG-7EO': '3,6,9,12,15,18-Hexaoxaicosane-1,20-diol',
    'PEG-8EO': 'Octaethylene glycol',
    'PEG-9EO': '3,6,9,12,15,18,21,24-Octaoxahexacosan-1-OL',
    'Phenylalanylisoleucine (isomer of 1329)': 'JWBLQDDHSDGEGR-UHFFFAOYSA-N',
    'Propenyl thiosulfate (isomer of 108)': 'RUVGQUCSWPRGRF-UHFFFAOYSA-N',
    'Sodium 4-hydroxy-benzoate': '4-Hydroxybenzoic acid',  # modified to avoid ions
    'Succinic acid (not validated)': 'KDYFGRWQOYBRFD-UHFFFAOYSA-N',
    'Threonylleucine (isomer of 809, 926)': 'BQBCIBCLXBKYHW-UHFFFAOYSA-N',
    'trans-Petroselinic acid': 'Petroselaidic acid',
    'α-Aspartylphenylalanine': 'L-Aspartyl-L-phenylalanine',
    'α-Cyano-3-hydroxycinnamic acid': 'alpha-Cyano-3-hydroxycinnamic acid',
    'δ-Valerolactam': '2-Piperidone',
    '4-(2,3-dihydroxy-3-methylbutoxy)-7H-furo[3,2-g]chromen-7-one':
        '4-(2,3-Dihydroxy-3-methylbutoxy)furo(3,2-g)chromen-7-one',
    '1-Isopropenyl-2,3-dihydro-1H-benzo[d]imidazol-2-one':
        '1-(prop-1-en-2-yl)-1H-benzo[d]imidazol-2(3H)-one',
}
snf_names_dic = {'N-N-diethyl-3-methylbenzamide (DEET)': 'Diethyltoluamide',
                 'N-Butyl-4-chloro-N-ethylbenzamide (BEclB)': 'N-Butyl-4-chloro-N-ethylbenzamide',
                 'Metoclopramid': 'Metoclopramide',
                 'Irgarol 1051 (Cybutryn)': 'Cybutryne',
                 'Cyclamate (Cyclamic acid)': 'Cyclamic acid',
                 '4-Chloro-N,N-Dimethylbenzamide (MMclB)': '4-Chloro-N,N-Dimethylbenzamide',
                 'Rufinamid': 'Rufinamide',
                 'Tebutam, Butam': 'Tebutam',
                 'Canagliflozin hydrate': 'Canagliflozin',
                 }

amar_dic = {'amar_lug': ['lug', '109 till 113', 'Australia', 'AUS1', 'AS'],
            'amar_gat': ['gat', '115 till 116', 'Australia', 'AUS2', 'lagoon'],
            'amar_wer': ['wer', '105 till 106', 'Switzerland', 'CH1', 'AS'],
            'amar_neu': ['neu', '132 till 133', 'Switzerland', 'CH2', 'AS'],
            'amar_enk': ['enk', '87 till 86', 'Sweden', 'SE1', 'AS'],
            'amar_kap': ['kap', '96 till 97', 'Sweden', 'SE2', 'AS'],
            'amar_kat': ['kat', '100 till 101', 'Sweden', 'SE3', 'MBBR']}

aus_amar_names_dic = {'4-(2,3-dihydroxy-3-methylbutoxy)-7H-furo[3,2-g]chromen-7-one':
                      '4-(2,3-Dihydroxy-3-methylbutoxy)furo(3,2-g)chromen-7-one'}

galpro_names_dic = {'Pregabalin-rac':'Pregabalin',
                    '5-Methyl-Benzotriazol':'5-Methyl-1H-benzotriazole',
                    'Phenazon (Antipyrin- ID 2519)':'Phenazone',
                    'Acamprosat':'Acamprosate',
                    'Oxcarbazepin':'Oxcarbazepine'}
