import pandas as pd

class Assumptionlog:	
	assumptionlog: pd.Series
	description: pd.Series
	discipline: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_assumptionlog: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	impact: pd.Series
	isopen: pd.Series
	manager: pd.Series
	monitoring: pd.Series
	owner: pd.Series
	project: pd.Series
	projectcode_assumptionlog: pd.Series
	realclosingdate: pd.Series
class Corpschedule:	
	active: pd.Series
	corpschedule: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_corpschedule: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
class Corpschedule2wellevent:	
	corpschedule: pd.Series
	corpscheduleversion: pd.Series
	corpscheduleversioncode: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	end: pd.Series
	hcode_corpschedule2wellevent: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	projectwell: pd.Series
	projectwellcode: pd.Series
	start: pd.Series
	welleventresource: pd.Series
	welleventtype: pd.Series
class Corpscheduleversion:	
	closedate: pd.Series
	corpschedule: pd.Series
	corpscheduleversion: pd.Series
	corpscheduleversioncode: pd.Series
	default: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_corpscheduleversion: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	milestonecode: pd.Series
	open: pd.Series
	version: pd.Series
class Designconstraint:	
	description: pd.Series
	designconstraint: pd.Series
	designconstrainttype: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_designconstraint: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	project: pd.Series
	projectcode_designconstraint: pd.Series
	projectphase: pd.Series
	unit: pd.Series
	value: pd.Series
class Economiccase:	
	closedate: pd.Series
	economiccase: pd.Series
	economiccasecode: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_economiccase: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	open: pd.Series
	portfolio: pd.Series
	project: pd.Series
	projectcode_economiccase: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
class Economiccasecapexresult:	
	economiccase: pd.Series
	economiccaseresult: pd.Series
	economiccaseresultcode: pd.Series
	economiccaseversion: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	expweightedyearlycapex: pd.Series
	hcode_economiccasecapexresult: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	nwicase: pd.Series
	project: pd.Series
	projectcode_economiccasecapexresult: pd.Series
	strategy: pd.Series
	type: pd.Series
	year: pd.Series
class Economiccaseparametersbyfluid:	
	economiccase: pd.Series
	economiccaseversion: pd.Series
	economiccaseversioncode: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	equivalentcoef: pd.Series
	fluidtype: pd.Series
	gasheatcapacity: pd.Series
	hcode_economiccaseparametersbyfluid: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	project: pd.Series
	projectcode_economiccaseparametersbyfluid: pd.Series
	royalty: pd.Series
	salestax: pd.Series
	sellingprice: pd.Series
	strategy: pd.Series
	variable_opex: pd.Series
class Economiccaseprdresult:	
	economiccase: pd.Series
	economiccaseresult: pd.Series
	economiccaseresultcode: pd.Series
	economiccaseversion: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	expweightedyearlyproduction: pd.Series
	expweightedyearlyproductioneq: pd.Series
	fluidtype: pd.Series
	grossincome: pd.Series
	hcode_economiccaseprdresult: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	nwicase: pd.Series
	prdopex: pd.Series
	project: pd.Series
	projectcode_economiccaseprdresult: pd.Series
	royalty: pd.Series
	salestax: pd.Series
	strategy: pd.Series
	year: pd.Series
class Economiccaseresult:	
	economiccase: pd.Series
	economiccaseresult: pd.Series
	economiccaseresultcode: pd.Series
	economiccaseversion: pd.Series
	economiccaseversioncode: pd.Series
	economicscenario: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	evdate: pd.Series
	expectedcapex: pd.Series
	expectedcapexnwi: pd.Series
	expectedfandd: pd.Series
	expectedfanddnwi: pd.Series
	expectedirr: pd.Series
	expectedirrnwi: pd.Series
	expectedlifttingcost: pd.Series
	expectedlifttingcostnwi: pd.Series
	expectednpv: pd.Series
	expectednpvnwi: pd.Series
	expectedpayback: pd.Series
	expectedpaybacknwi: pd.Series
	expectedpindex: pd.Series
	expectedpindexnwi: pd.Series
	expectedprdeq: pd.Series
	expectedprdeqnwi: pd.Series
	hcode_economiccaseresult: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	p10capex: pd.Series
	p10capexnwi: pd.Series
	p10fandd: pd.Series
	p10fanddnwi: pd.Series
	p10irr: pd.Series
	p10irrnwi: pd.Series
	p10lifttingcost: pd.Series
	p10lifttingcostnwi: pd.Series
	p10npv: pd.Series
	p10npvnwi: pd.Series
	p10payback: pd.Series
	p10paybacknwi: pd.Series
	p10pindex: pd.Series
	p10pindexnwi: pd.Series
	p10prdeq: pd.Series
	p10prdeqnwi: pd.Series
	p50capex: pd.Series
	p50capexnwi: pd.Series
	p50fandd: pd.Series
	p50fanddnwi: pd.Series
	p50irr: pd.Series
	p50irrnwi: pd.Series
	p50lifttingcost: pd.Series
	p50lifttingcostnwi: pd.Series
	p50npv: pd.Series
	p50npvnwi: pd.Series
	p50payback: pd.Series
	p50paybacknwi: pd.Series
	p50pindex: pd.Series
	p50pindexnwi: pd.Series
	p50prdeq: pd.Series
	p50prdeqnwi: pd.Series
	p90capex: pd.Series
	p90capexnwi: pd.Series
	p90fandd: pd.Series
	p90fanddnwi: pd.Series
	p90irr: pd.Series
	p90irrnwi: pd.Series
	p90lifttingcost: pd.Series
	p90lifttingcostnwi: pd.Series
	p90npv: pd.Series
	p90npvnwi: pd.Series
	p90payback: pd.Series
	p90paybacknwi: pd.Series
	p90pindex: pd.Series
	p90pindexnwi: pd.Series
	p90prdeq: pd.Series
	p90prdeqnwi: pd.Series
	project: pd.Series
	projectcode_economiccaseresult: pd.Series
	resourcecategory: pd.Series
	resourceclass: pd.Series
	strategy: pd.Series
class Economiccaseversion:	
	default: pd.Series
	description: pd.Series
	economiccase: pd.Series
	economiccasecode: pd.Series
	economiccaseversion: pd.Series
	economiccaseversioncode: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	firstyear: pd.Series
	firstyearfraction: pd.Series
	fixed_opex_nwifraction: pd.Series
	fixed_opex_yearly: pd.Series
	hcode_economiccaseversion: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	incometax: pd.Series
	project: pd.Series
	projectcode_economiccaseversion: pd.Series
	strategy: pd.Series
	version: pd.Series
	wacc: pd.Series
	yearevstart: pd.Series
class Economiccasewelleventcountresult:	
	economiccase: pd.Series
	economiccaseresult: pd.Series
	economiccaseresultcode: pd.Series
	economiccaseversion: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	event: pd.Series
	hcode_economiccasewelleventcountresult: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	nwicase: pd.Series
	project: pd.Series
	projectcode_economiccasewelleventcountresult: pd.Series
	strategy: pd.Series
	year: pd.Series
	yearlyeventcountweighted: pd.Series
class Facility:	
	active: pd.Series
	closedate: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	facility: pd.Series
	facilityclass: pd.Series
	facilitystatus: pd.Series
	hcode_facility: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	isblocked: pd.Series
	milestonecode: pd.Series
	xcoord: pd.Series
	ycoord: pd.Series
	zcoord: pd.Series
class Facilitycapacity:	
	capacity: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	facility: pd.Series
	fluidclass: pd.Series
	hcode_facilitycapacity: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	startdate: pd.Series
class Field:	
	acronym: pd.Series
	active: pd.Series
	area: pd.Series
	basin: pd.Series
	closedate: pd.Series
	concession: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	entitlementenddate: pd.Series
	entitlementstartdate: pd.Series
	entity: pd.Series
	field: pd.Series
	hcode_field: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	isblocked: pd.Series
	isoffshore: pd.Series
	milestonecode: pd.Series
	xcoord: pd.Series
	ycoord: pd.Series
	zcoord: pd.Series
class Fluidtype:	
	color: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	fluidclass: pd.Series
	fluidtype: pd.Series
	hcode_fluidtype: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	isresource: pd.Series
	isselected: pd.Series
class Huorganization:	
	accountactivation: pd.Series
	accountpaused: pd.Series
	askedfordeletion: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	grouplevel: pd.Series
	hcode_huorganization: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	level1: pd.Series
	level2: pd.Series
	level3: pd.Series
	level4: pd.Series
	level5: pd.Series
	uniqueclientcode: pd.Series
	uniqueclientname: pd.Series
class Investmentcode:	
	code: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_investmentcode: pd.Series
	hierarchicalorg: pd.Series
	hierarchicalorg2: pd.Series
	id: pd.Series
	investment: pd.Series
	project: pd.Series
	projectcode_investmentcode: pd.Series
class Issuelog:	
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_issuelog: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	isopen: pd.Series
	issuelog: pd.Series
	issuesubtype: pd.Series
	issuetype: pd.Series
	manager: pd.Series
	owner: pd.Series
	plannedduedate: pd.Series
	postdate: pd.Series
	priority: pd.Series
	project: pd.Series
	projectcode_issuelog: pd.Series
	projectphase: pd.Series
	realclosingdate: pd.Series
	resolution: pd.Series
class Lessonlearned:	
	description: pd.Series
	discipline: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_lessonlearned: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	isopen: pd.Series
	lessonlearned: pd.Series
	manager: pd.Series
	owner: pd.Series
	postdate: pd.Series
	project: pd.Series
	projectcode_lessonlearned: pd.Series
	projectphase: pd.Series
	realclosingdate: pd.Series
class Milestone:	
	basecode: pd.Series
	closedate: pd.Series
	description: pd.Series
	duedate: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	evend: pd.Series
	evstart: pd.Series
	hcode_milestone: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	milestone: pd.Series
	milestonecode: pd.Series
	milestonefrequencyacronym: pd.Series
	milestonetype: pd.Series
	open: pd.Series
	opendate: pd.Series
	project: pd.Series
	projectcode_milestone: pd.Series
	resourcestartdate: pd.Series
	yearplan: pd.Series
class Milestoneversion:	
	alldecisionsmade: pd.Series
	approvedby: pd.Series
	decisiondate: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_milestoneversion: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	isapproved: pd.Series
	isselected: pd.Series
	milestone: pd.Series
	milestonecode: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	presentationdate: pd.Series
	presentedby: pd.Series
	project: pd.Series
	projectcode_milestoneversion: pd.Series
	version: pd.Series
class Milestoneversion2strategy:	
	defaultmstversion: pd.Series
	hcode_milestoneversion2strategy: pd.Series
	hierarchicalorg: pd.Series
	milestone: pd.Series
	milestonecode: pd.Series
	milestoneid: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	milestoneversionid: pd.Series
	project: pd.Series
	projectcode_milestoneversion2strategy: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	strategyid: pd.Series
class Otherinvestment:	
	closedate: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_otherinvestment: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	investmenttype: pd.Series
	isblocked: pd.Series
	milestonecode: pd.Series
	otherinvestment: pd.Series
	otherinvestmentcode: pd.Series
	project: pd.Series
	projectcode_otherinvestment: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
class Otherinvestmentmilestone:	
	bestorexpcost: pd.Series
	bestorexptime: pd.Series
	capextimeallocfactor: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	enddate: pd.Series
	facility: pd.Series
	hcode_otherinvestmentmilestone: pd.Series
	hierarchicalorg: pd.Series
	highcost: pd.Series
	hightime: pd.Series
	id: pd.Series
	inputmethod: pd.Series
	investmentcode: pd.Series
	isselected: pd.Series
	isstrategy_: pd.Series
	lowcost: pd.Series
	lowtime: pd.Series
	milestone: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	otherinvestment: pd.Series
	otherinvestmentcode: pd.Series
	project: pd.Series
	project2reservoirtarget: pd.Series
	project2reservoirtargetcode: pd.Series
	projectcode_otherinvestmentmilestone: pd.Series
	projectphase: pd.Series
	projectwell: pd.Series
	projectwellcode: pd.Series
	resourcecategory: pd.Series
	risk: pd.Series
	riskcapital: pd.Series
	riskcode: pd.Series
	startdate: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	updtoactualcost: pd.Series
class Prdzone:	
	compressibility: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	grosspay: pd.Series
	hcode_prdzone: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	netpay: pd.Series
	permeability: pd.Series
	porosity: pd.Series
	prdzone: pd.Series
	prdzonecode: pd.Series
	project: pd.Series
	projectcode_prdzone: pd.Series
	sg: pd.Series
	so: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	sw: pd.Series
class Project:	
	acronym: pd.Series
	active: pd.Series
	capexinputmethod: pd.Series
	capextimeallocfactor: pd.Series
	code: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	entity: pd.Series
	executivesummary: pd.Series
	facility: pd.Series
	fluidtype: pd.Series
	hcode_project: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	isgreenfield: pd.Series
	prdinputmethod: pd.Series
	project: pd.Series
	projectclass: pd.Series
	projectcode: pd.Series
	projectcode_project: pd.Series
class Project2chanceofcommerciality:	
	chanceofacquisition: pd.Series
	chanceofcommerciality_: pd.Series
	chanceofdevelopment: pd.Series
	chanceofdiscovery: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_project2chanceofcommerciality: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	milestone: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	project: pd.Series
	project2reservoirtarget: pd.Series
	project2reservoirtargetcode: pd.Series
	projectcode_project2chanceofcommerciality: pd.Series
	resourceclass: pd.Series
class Project2features:	
	approvalstatus: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_project2features: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	milestone: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	project: pd.Series
	projectcode_project2features: pd.Series
	projectphase: pd.Series
	projectsubphase: pd.Series
	projecttype: pd.Series
	resourceclass: pd.Series
class Project2partner:	
	editedbyuser: pd.Series
	editiondate: pd.Series
	entity: pd.Series
	hcode_project2partner: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	investmenttype: pd.Series
	milestone: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	networkingint: pd.Series
	project: pd.Series
	projectcode_project2partner: pd.Series
class Project2productionshare:	
	editedbyuser: pd.Series
	editiondate: pd.Series
	entity: pd.Series
	fluidtype: pd.Series
	hcode_project2productionshare: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	milestone: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	productionshare: pd.Series
	project: pd.Series
	projectcode_project2productionshare: pd.Series
class Project2reservoirtarget:	
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_project2reservoirtarget: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	project: pd.Series
	project2reservoirtarget: pd.Series
	project2reservoirtargetcode: pd.Series
	projectcode_project2reservoirtarget: pd.Series
	reservoir: pd.Series
class Project2user2role:	
	datesignout: pd.Series
	datesignup: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_project2user2role: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	portfoliorole: pd.Series
	project: pd.Series
	projectcode_project2user2role: pd.Series
	user: pd.Series
class Projectcharter:	
	benefitsplan: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	exitcriteria: pd.Series
	hcode_projectcharter: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	opstatement: pd.Series
	project: pd.Series
	projectcode_projectcharter: pd.Series
	projectdescrip: pd.Series
	strategicfit: pd.Series
	successcriteria: pd.Series
class Projectdeliverable:	
	description: pd.Series
	discipline: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_projectdeliverable: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	isopen: pd.Series
	manager: pd.Series
	monitoring: pd.Series
	owner: pd.Series
	plannedduedate: pd.Series
	project: pd.Series
	projectcode_projectdeliverable: pd.Series
	projectdeliverable: pd.Series
	projectphase: pd.Series
	realclosingdate: pd.Series
class Projectphase:	
	acronym: pd.Series
	costclass: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	goal: pd.Series
	hcode_projectphase: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	isclose: pd.Series
	islaunch: pd.Series
	projectphase: pd.Series
	sequence: pd.Series
class Projectroadmap:	
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	enddate: pd.Series
	hcode_projectroadmap: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	project: pd.Series
	projectcode_projectroadmap: pd.Series
	projectphase: pd.Series
	realenddate: pd.Series
	realstartdate: pd.Series
	startdate: pd.Series
class Projectschedule:	
	corpscheduleversion: pd.Series
	corpscheduleversioncode: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_projectschedule: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	project: pd.Series
	projectcode_projectschedule: pd.Series
	projectschedule: pd.Series
	projectschedulecode: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
class Projectschedule2wellevent:	
	editedbyuser: pd.Series
	editiondate: pd.Series
	eventcancelled: pd.Series
	hcode_projectschedule2wellevent: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	project: pd.Series
	projectcode_projectschedule2wellevent: pd.Series
	projectschedule: pd.Series
	projectschedulecode: pd.Series
	projectwell: pd.Series
	projectwellcode: pd.Series
	proposeend: pd.Series
	proposestart: pd.Series
	strategy: pd.Series
	welleventtype: pd.Series
class Projectschedule2welltiein:	
	calculatedassocinvend: pd.Series
	calculatedassocwellend: pd.Series
	calculatedprdstartdate: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_projectschedule2welltiein: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	otherinvestment: pd.Series
	otherinvestmentcode: pd.Series
	prdcancelled: pd.Series
	project: pd.Series
	projectcode_projectschedule2welltiein: pd.Series
	projectschedule: pd.Series
	projectschedulecode: pd.Series
	projectwell: pd.Series
	projectwell2: pd.Series
	projectwell2code: pd.Series
	projectwellcode: pd.Series
	proplasteventend: pd.Series
	realprddaysfirstmonth: pd.Series
	realprdmonthstart: pd.Series
	strategy: pd.Series
	tieindays: pd.Series
	updrealprdmonthstart: pd.Series
class Projectwellmilestone:	
	blockmatching: pd.Series
	calculatedblockmatching: pd.Series
	calculatedwellalias: pd.Series
	calculatedwellalias2: pd.Series
	calculatedwellmaster: pd.Series
	calculatedwellmastermatch: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	field: pd.Series
	hcode_projectwellmilestone: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	investmentcode: pd.Series
	isselected: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	project: pd.Series
	projectcode_projectwellmilestone: pd.Series
	projectphase: pd.Series
	projectwell: pd.Series
	projectwell2: pd.Series
	projectwell2code: pd.Series
	projectwellcode: pd.Series
	riskcapital: pd.Series
	sequence: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	uniqueuserwellalias: pd.Series
	updtoactualcost: pd.Series
	userbisnumber: pd.Series
	userwellalias: pd.Series
	userwellnumber: pd.Series
	usespecificwelldesign: pd.Series
	wellacronym: pd.Series
	welldesignversion: pd.Series
	welldesignversion2code: pd.Series
	welldesignversioncode: pd.Series
	wellmaster: pd.Series
	wellstrategy: pd.Series
	xcoordbottomhole: pd.Series
	xcoordwellhead: pd.Series
	ycoordbottomhole: pd.Series
	ycoordwellhead: pd.Series
	yearplan: pd.Series
	zcoordbottomhole: pd.Series
	zcoordwellhead: pd.Series
	zone: pd.Series
	zonecode: pd.Series
class Projectwellmilestone2reservoir:	
	autoassignp1: pd.Series
	basecurveversion: pd.Series
	basecurveversioncode: pd.Series
	curvefactor: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	facility: pd.Series
	hcode_projectwellmilestone2reservoir: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	prdzone: pd.Series
	prdzonecode: pd.Series
	project: pd.Series
	project2reservoirtarget: pd.Series
	project2reservoirtargetcode: pd.Series
	projectcode_projectwellmilestone2reservoir: pd.Series
	projectwell: pd.Series
	projectwellcode: pd.Series
	realprdfitoption: pd.Series
	reservestatus: pd.Series
	resourcecategory: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	typecurveversion: pd.Series
	typecurveversioncode: pd.Series
	usebasecurve: pd.Series
	usewellcurve: pd.Series
	wellcurveversion: pd.Series
	wellcurveversioncode: pd.Series
class Publishedcost:	
	actualcost: pd.Series
	bestorexpplannedcost: pd.Series
	bestorexpplannedcostnwi: pd.Series
	bestorexpplannedcostweighted: pd.Series
	bestorexpplannedcostweightednwi: pd.Series
	bestorexpplannedtime: pd.Series
	defaultmstversion: pd.Series
	end: pd.Series
	eventcancelled: pd.Series
	expplannedcost: pd.Series
	expplannedcostnwi: pd.Series
	expplannedcostweighted: pd.Series
	expplannedcostweightednwi: pd.Series
	expplannedtime: pd.Series
	hcode_publishedcost: pd.Series
	hierarchicalorg: pd.Series
	highplannedcost: pd.Series
	highplannedcostnwi: pd.Series
	highplannedcostweighted: pd.Series
	highplannedcostweightednwi: pd.Series
	highplannedtime: pd.Series
	investment: pd.Series
	investmentcode: pd.Series
	investmentselected: pd.Series
	investmenttype: pd.Series
	isstrategy_: pd.Series
	lastdateactualcost: pd.Series
	lowplannedcost: pd.Series
	lowplannedcostnwi: pd.Series
	lowplannedcostweighted: pd.Series
	lowplannedcostweightednwi: pd.Series
	lowplannedtime: pd.Series
	milestone: pd.Series
	milestonecode: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	project: pd.Series
	projectcode_publishedcost: pd.Series
	realtime: pd.Series
	relativestddevplannedcost: pd.Series
	relativestddevplannedtime: pd.Series
	selectedstrategy: pd.Series
	start: pd.Series
	stddevplannedcost: pd.Series
	stddevplannedcostnwi: pd.Series
	stddevplannedcostweighted: pd.Series
	stddevplannedcostweightednwi: pd.Series
	stddevplannedtime: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	wellalias: pd.Series
	wellalias2: pd.Series
	welleventtype: pd.Series
	year: pd.Series
class Publishedcostcurve:	
	actualcost: pd.Series
	bestorexpplannedcost: pd.Series
	bestorexpplannedcostnwi: pd.Series
	bestorexpplannedcostweighted: pd.Series
	bestorexpplannedcostweightednwi: pd.Series
	defaultmstversion: pd.Series
	eventcancelled: pd.Series
	expplannedcost: pd.Series
	expplannedcostnwi: pd.Series
	expplannedcostweighted: pd.Series
	expplannedcostweightednwi: pd.Series
	hcode_publishedcostcurve: pd.Series
	hierarchicalorg: pd.Series
	highplannedcost: pd.Series
	highplannedcostnwi: pd.Series
	highplannedcostweighted: pd.Series
	highplannedcostweightednwi: pd.Series
	investment: pd.Series
	investmentcode: pd.Series
	investmentselected: pd.Series
	investmenttype: pd.Series
	isstrategy_: pd.Series
	lowplannedcost: pd.Series
	lowplannedcostnwi: pd.Series
	lowplannedcostweighted: pd.Series
	lowplannedcostweightednwi: pd.Series
	milestone: pd.Series
	milestonecode: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	monthlydate: pd.Series
	project: pd.Series
	projectcode_publishedcostcurve: pd.Series
	selectedstrategy: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	wellalias: pd.Series
	wellalias2: pd.Series
	welleventtype: pd.Series
	year: pd.Series
class Publishedeurandreservesbywell:	
	c1: pd.Series
	c1_bas: pd.Series
	c2: pd.Series
	c2_bas: pd.Series
	c3: pd.Series
	c3_bas: pd.Series
	cresources: pd.Series
	cresources_bas: pd.Series
	detbasecumprd: pd.Series
	detbasecumprd_bas: pd.Series
	expbaselineeurweighted: pd.Series
	expbaselineeurweightedeq: pd.Series
	expbaselineeurweightednwi: pd.Series
	expbaselineeurweightednwieq: pd.Series
	expplannedeurweighted: pd.Series
	expplannedeurweightedeq: pd.Series
	expplannedeurweightednwi: pd.Series
	expplannedeurweightednwieq: pd.Series
	fluid: pd.Series
	forecastcumprd: pd.Series
	hcode_publishedeurandreservesbywell: pd.Series
	hierarchicalorg: pd.Series
	milestone: pd.Series
	milestonecode: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	p1: pd.Series
	p1_bas: pd.Series
	p10plannedeurweighted: pd.Series
	p1d: pd.Series
	p1d_bas: pd.Series
	p1u: pd.Series
	p1u_bas: pd.Series
	p2: pd.Series
	p2_bas: pd.Series
	p2d: pd.Series
	p2d_bas: pd.Series
	p2u: pd.Series
	p2u_bas: pd.Series
	p3: pd.Series
	p3_bas: pd.Series
	p3d: pd.Series
	p3d_bas: pd.Series
	p3u: pd.Series
	p3u_bas: pd.Series
	p50plannedeurweighted: pd.Series
	p90plannedeurweighted: pd.Series
	presources: pd.Series
	presources_bas: pd.Series
	prjrealcumprd: pd.Series
	project: pd.Series
	projectcode_publishedeurandreservesbywell: pd.Series
	projectschedule: pd.Series
	projectschedulecode: pd.Series
	projectwell: pd.Series
	projectwellcode: pd.Series
	realcumprd: pd.Series
	reserves: pd.Series
	reserves_bas: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	totalresource: pd.Series
	u1: pd.Series
	u1_bas: pd.Series
	u2: pd.Series
	u2_bas: pd.Series
	u3: pd.Series
	u3_bas: pd.Series
	wellalias: pd.Series
	wellalias2: pd.Series
class Publishedwellproduction:	
	autoassignp1: pd.Series
	basecurveversion: pd.Series
	basecurveversioncode: pd.Series
	c1: pd.Series
	c2: pd.Series
	c3: pd.Series
	chanceofcommerciality: pd.Series
	conversionfactor: pd.Series
	cresources: pd.Series
	cresources_eq: pd.Series
	cresources_nwi: pd.Series
	cresources_nwieq: pd.Series
	curvefactor: pd.Series
	defaultmstversion: pd.Series
	detbase: pd.Series
	detdplannedcurve: pd.Series
	detplannedcurve: pd.Series
	detplannedcurveweighted: pd.Series
	detplannedcurveweightedeq: pd.Series
	detplannedcurveweightednwi: pd.Series
	detplannedcurveweightednwieq: pd.Series
	dettype: pd.Series
	dettypeweighted: pd.Series
	detuplannedcurve: pd.Series
	detutype: pd.Series
	detuwell: pd.Series
	detwell: pd.Series
	detwellweighted: pd.Series
	expplannedcurve: pd.Series
	expplannedcurveweighted: pd.Series
	expplannedcurveweightedeq: pd.Series
	expplannedcurveweightednwi: pd.Series
	expplannedcurveweightednwieq: pd.Series
	exptype: pd.Series
	exptypeweighted: pd.Series
	expwell: pd.Series
	expwellweighted: pd.Series
	facility: pd.Series
	field: pd.Series
	fluid: pd.Series
	forecastprd: pd.Series
	formation: pd.Series
	hcode_publishedwellproduction: pd.Series
	hierarchicalorg: pd.Series
	isresource: pd.Series
	milestone: pd.Series
	milestonecode: pd.Series
	milestoneversion: pd.Series
	milestoneversioncode: pd.Series
	month: pd.Series
	monthlydate: pd.Series
	p1: pd.Series
	p1_eq: pd.Series
	p1_nwi: pd.Series
	p1_nwieq: pd.Series
	p10dplannedcurve: pd.Series
	p10plannedcurve: pd.Series
	p10plannedcurveweighted: pd.Series
	p10plannedcurveweightedeq: pd.Series
	p10plannedcurveweightednwi: pd.Series
	p10plannedcurveweightednwieq: pd.Series
	p10type: pd.Series
	p10typeweighted: pd.Series
	p10uplannedcurve: pd.Series
	p10utype: pd.Series
	p10uwell: pd.Series
	p10well: pd.Series
	p10wellweighted: pd.Series
	p1d: pd.Series
	p1u: pd.Series
	p2: pd.Series
	p2_eq: pd.Series
	p2_nwi: pd.Series
	p2_nwieq: pd.Series
	p2d: pd.Series
	p2u: pd.Series
	p3: pd.Series
	p3_eq: pd.Series
	p3_nwi: pd.Series
	p3_nwieq: pd.Series
	p3d: pd.Series
	p3u: pd.Series
	p50dplannedcurve: pd.Series
	p50plannedcurve: pd.Series
	p50plannedcurveweighted: pd.Series
	p50plannedcurveweightedeq: pd.Series
	p50plannedcurveweightednwi: pd.Series
	p50plannedcurveweightednwieq: pd.Series
	p50type: pd.Series
	p50typeweighted: pd.Series
	p50uplannedcurve: pd.Series
	p50utype: pd.Series
	p50uwell: pd.Series
	p50well: pd.Series
	p50wellweighted: pd.Series
	p90dplannedcurve: pd.Series
	p90plannedcurve: pd.Series
	p90plannedcurveweighted: pd.Series
	p90plannedcurveweightedeq: pd.Series
	p90plannedcurveweightednwi: pd.Series
	p90plannedcurveweightednwieq: pd.Series
	p90type: pd.Series
	p90typeweighted: pd.Series
	p90uplannedcurve: pd.Series
	p90utype: pd.Series
	p90uwell: pd.Series
	p90well: pd.Series
	p90wellweighted: pd.Series
	plannedcurvemethod: pd.Series
	prdzone: pd.Series
	prdzonecode: pd.Series
	presources: pd.Series
	presources_eq: pd.Series
	presources_nwi: pd.Series
	presources_nwieq: pd.Series
	prjrealprdcalday: pd.Series
	prjrealprdcaldayweighted: pd.Series
	prjrealprdcaldayweightedeq: pd.Series
	prjrealprdcaldayweightednwi: pd.Series
	prjrealprdcaldayweightednwieq: pd.Series
	productionshare: pd.Series
	project: pd.Series
	project2reservoirtarget: pd.Series
	project2reservoirtargetcode: pd.Series
	projectcode_publishedwellproduction: pd.Series
	projectschedule: pd.Series
	projectschedulecode: pd.Series
	projectwell: pd.Series
	projectwellcode: pd.Series
	realfitoption: pd.Series
	realprdcalday: pd.Series
	realprdproday: pd.Series
	reserves: pd.Series
	reserves_eq: pd.Series
	reserves_nwi: pd.Series
	reserves_nwieq: pd.Series
	reservestatus: pd.Series
	resourcecategory: pd.Series
	resourcecategorybis: pd.Series
	resourceclass: pd.Series
	resourceclassbis: pd.Series
	resourceprob: pd.Series
	selectedstrategy: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	typecurvemethod: pd.Series
	typecurveversion: pd.Series
	typecurveversioncode: pd.Series
	u1: pd.Series
	u2: pd.Series
	u3: pd.Series
	usebasecurve: pd.Series
	usewellcurve: pd.Series
	wellalias: pd.Series
	wellalias2: pd.Series
	wellcurvemethod: pd.Series
	wellcurveversion: pd.Series
	wellcurveversioncode: pd.Series
	year: pd.Series
	zone: pd.Series
	zonecode: pd.Series
class Reservoir:	
	area: pd.Series
	avgdepth: pd.Series
	closedate: pd.Series
	compressibility: pd.Series
	description: pd.Series
	drivemechanism: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	entity: pd.Series
	field: pd.Series
	fluidtype: pd.Series
	formation: pd.Series
	grosspay: pd.Series
	hcode_reservoir: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	initialpressure: pd.Series
	isblocked: pd.Series
	milestonecode: pd.Series
	netpay: pd.Series
	permeability: pd.Series
	porosity: pd.Series
	refdepth: pd.Series
	reservoir: pd.Series
	resourcetype: pd.Series
	rocktype: pd.Series
	sg: pd.Series
	so: pd.Series
	sw: pd.Series
	temperature: pd.Series
	wellacronym: pd.Series
class Reservoir2fluid:	
	conversionfactor: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	expohip: pd.Series
	field: pd.Series
	fluidtype: pd.Series
	hcode_reservoir2fluid: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	p10ohip: pd.Series
	p50ohip: pd.Series
	p90ohip: pd.Series
	reservoir: pd.Series
class Risk:	
	bestorexpvalue: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_risk: pd.Series
	hierarchicalorg: pd.Series
	highvalue: pd.Series
	id: pd.Series
	identity: pd.Series
	impact: pd.Series
	isopen: pd.Series
	isopportunity: pd.Series
	lowvalue: pd.Series
	manager: pd.Series
	monitoring: pd.Series
	owner: pd.Series
	prioritization: pd.Series
	probability: pd.Series
	project: pd.Series
	projectcode_risk: pd.Series
	projectphase: pd.Series
	realclosingdate: pd.Series
	risk: pd.Series
	riskcategory: pd.Series
	riskcode: pd.Series
	riskresponsetype: pd.Series
	risksubtype: pd.Series
	risktype: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	unit: pd.Series
	valuation_: pd.Series
class Staffplan:	
	editedbyuser: pd.Series
	editiondate: pd.Series
	fulltimeequivalent: pd.Series
	hcode_staffplan: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	portfoliorole: pd.Series
	project: pd.Series
	projectcode_staffplan: pd.Series
	projectphase: pd.Series
	userexpertise: pd.Series
class Stakeholder:	
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	expectations: pd.Series
	hcode_stakeholder: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	interest: pd.Series
	isblocker: pd.Series
	isopen: pd.Series
	levelofinfluence_: pd.Series
	manager: pd.Series
	mgmtplan: pd.Series
	monitoring: pd.Series
	owner: pd.Series
	power: pd.Series
	project: pd.Series
	projectcode_stakeholder: pd.Series
	realclosingdate: pd.Series
	requirements: pd.Series
	stakeholder: pd.Series
	stakeholderclass: pd.Series
class Strategy:	
	acronym: pd.Series
	active: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	floodpattern: pd.Series
	hcode_strategy: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	improvedrecovery: pd.Series
	isselected: pd.Series
	project: pd.Series
	projectcode_strategy: pd.Series
	recoveryclass: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	wellspacing: pd.Series
class Strategy2guidelines:	
	description: pd.Series
	discipline: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_strategy2guidelines: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	monitoring: pd.Series
	project: pd.Series
	projectcode_strategy2guidelines: pd.Series
	strategy: pd.Series
	strategy2guidelines: pd.Series
	strategycode: pd.Series
class Strategy2zone:	
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_strategy2zone: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	project: pd.Series
	projectcode_strategy2zone: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	zone: pd.Series
	zonecode: pd.Series
class Valuedriver:	
	description: pd.Series
	discipline: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_valuedriver: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	influence: pd.Series
	isopen: pd.Series
	manager: pd.Series
	monitoring: pd.Series
	owner: pd.Series
	project: pd.Series
	projectcode_valuedriver: pd.Series
	realclosingdate: pd.Series
	valuedriver: pd.Series
class Wellcurve:	
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_wellcurve: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	isbase: pd.Series
	prdzone: pd.Series
	prdzonecode: pd.Series
	project: pd.Series
	project2reservoirtarget: pd.Series
	project2reservoirtargetcode: pd.Series
	projectcode_wellcurve: pd.Series
	projectwell: pd.Series
	projectwellcode: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	wellclass: pd.Series
	wellcurve: pd.Series
	wellcurvecode: pd.Series
class Wellcurvefactor:	
	editedbyuser: pd.Series
	editiondate: pd.Series
	factor: pd.Series
	hcode_wellcurvefactor: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	month: pd.Series
	project: pd.Series
	projectcode_wellcurvefactor: pd.Series
	strategy: pd.Series
	wellcurve: pd.Series
	wellcurvefluid: pd.Series
	wellcurvefluid2: pd.Series
	wellcurvefluid2code: pd.Series
	wellcurvefluidcode: pd.Series
	wellcurveversion: pd.Series
	wellcurveversioncode: pd.Series
class Wellcurvefluid:	
	designdate: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	fluidtype: pd.Series
	hcode_wellcurvefluid: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	project: pd.Series
	projectcode_wellcurvefluid: pd.Series
	strategy: pd.Series
	typeofcurve: pd.Series
	wellcurve: pd.Series
	wellcurvefluid: pd.Series
	wellcurvefluidcode: pd.Series
	wellcurveversion: pd.Series
	wellcurveversioncode: pd.Series
class Wellcurveparametric:	
	detdb: pd.Series
	detdd: pd.Series
	detdequationtype: pd.Series
	detdinitialratetype: pd.Series
	detdmonths: pd.Series
	detdqi: pd.Series
	detdqmin: pd.Series
	detub: pd.Series
	detud: pd.Series
	detuequationtype: pd.Series
	detuinitialratetype: pd.Series
	detumonths: pd.Series
	detuqi: pd.Series
	detuqmin: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_wellcurveparametric: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	p10db: pd.Series
	p10dd: pd.Series
	p10dequationtype: pd.Series
	p10dinitialratetype: pd.Series
	p10dmonths: pd.Series
	p10dqi: pd.Series
	p10dqmin: pd.Series
	p10ub: pd.Series
	p10ud: pd.Series
	p10uequationtype: pd.Series
	p10uinitialratetype: pd.Series
	p10umonths: pd.Series
	p10uqi: pd.Series
	p10uqmin: pd.Series
	p50db: pd.Series
	p50dd: pd.Series
	p50dequationtype: pd.Series
	p50dinitialratetype: pd.Series
	p50dmonths: pd.Series
	p50dqi: pd.Series
	p50dqmin: pd.Series
	p50ub: pd.Series
	p50ud: pd.Series
	p50uequationtype: pd.Series
	p50uinitialratetype: pd.Series
	p50umonths: pd.Series
	p50uqi: pd.Series
	p50uqmin: pd.Series
	p90db: pd.Series
	p90dd: pd.Series
	p90dequationtype: pd.Series
	p90dinitialratetype: pd.Series
	p90dmonths: pd.Series
	p90dqi: pd.Series
	p90dqmin: pd.Series
	p90ub: pd.Series
	p90ud: pd.Series
	p90uequationtype: pd.Series
	p90uinitialratetype: pd.Series
	p90umonths: pd.Series
	p90uqi: pd.Series
	p90uqmin: pd.Series
	project: pd.Series
	projectcode_wellcurveparametric: pd.Series
	section: pd.Series
	strategy: pd.Series
	wellcurve: pd.Series
	wellcurvefluid: pd.Series
	wellcurvefluidcode: pd.Series
	wellcurveversion: pd.Series
	wellcurveversioncode: pd.Series
class Wellcurvevalue:	
	detdvol: pd.Series
	detuvol: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_wellcurvevalue: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	month: pd.Series
	p10dvol: pd.Series
	p10uvol: pd.Series
	p50dvol: pd.Series
	p50uvol: pd.Series
	p90dvol: pd.Series
	p90uvol: pd.Series
	project: pd.Series
	projectcode_wellcurvevalue: pd.Series
	strategy: pd.Series
	wellcurve: pd.Series
	wellcurvefluid: pd.Series
	wellcurvefluidcode: pd.Series
	wellcurveversion: pd.Series
	wellcurveversioncode: pd.Series
class Wellcurveversion:	
	bhflowingpressure: pd.Series
	closedate: pd.Series
	default: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_wellcurveversion: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	inputmethod: pd.Series
	milestonecode: pd.Series
	open: pd.Series
	project: pd.Series
	projectcode_wellcurveversion: pd.Series
	staticpressure: pd.Series
	strategy: pd.Series
	version: pd.Series
	wellcurve: pd.Series
	wellcurvecode: pd.Series
	wellcurveversion: pd.Series
	wellcurveversioncode: pd.Series
	whflowingpressure: pd.Series
class Welldesign:	
	artificiallift: pd.Series
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_welldesign: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	project: pd.Series
	projectcode_welldesign: pd.Series
	projectwell: pd.Series
	projectwellcode: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	typeofprojectwell: pd.Series
	wellclass: pd.Series
	welldesign: pd.Series
	welldesigncode: pd.Series
	welltrajectory: pd.Series
class Welldesigncost:	
	bestorexpcost: pd.Series
	bestorexptime: pd.Series
	capexinputmethod: pd.Series
	capextimeallocfactor: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_welldesigncost: pd.Series
	hierarchicalorg: pd.Series
	highcost: pd.Series
	hightime: pd.Series
	id: pd.Series
	lowcost: pd.Series
	lowtime: pd.Series
	project: pd.Series
	projectcode_welldesigncost: pd.Series
	strategy: pd.Series
	strategycode: pd.Series
	welldesignversion: pd.Series
	welldesignversioncode: pd.Series
	welleventtype: pd.Series
class Welldesignversion:	
	closedate: pd.Series
	default: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_welldesignversion: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	milestonecode: pd.Series
	open: pd.Series
	project: pd.Series
	projectcode_welldesignversion: pd.Series
	strategy: pd.Series
	version: pd.Series
	welldesign: pd.Series
	welldesigncode: pd.Series
	welldesignversion: pd.Series
	welldesignversioncode: pd.Series
class Wellmaster:	
	bisnumber: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	field: pd.Series
	hcode_wellmaster: pd.Series
	hierarchicalorg: pd.Series
	hierarchicalorg2: pd.Series
	id: pd.Series
	longname: pd.Series
	wellmaster: pd.Series
	wellnumber: pd.Series
	wellstrategy: pd.Series
	welltrajectory: pd.Series
	xcoordbottomhole: pd.Series
	xcoordwellhead: pd.Series
	ycoordbottomhole: pd.Series
	ycoordwellhead: pd.Series
	zcoordbottomhole: pd.Series
	zcoordwellhead: pd.Series
class Zone:	
	description: pd.Series
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_zone: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	identity: pd.Series
	project: pd.Series
	projectcode_zone: pd.Series
	wellcorrcoef: pd.Series
	zone: pd.Series
	zonecode: pd.Series
class Zone2reservoirtarget:	
	editedbyuser: pd.Series
	editiondate: pd.Series
	hcode_zone2reservoirtarget: pd.Series
	hierarchicalorg: pd.Series
	id: pd.Series
	project: pd.Series
	project2reservoirtarget: pd.Series
	project2reservoirtargetcode: pd.Series
	projectcode_zone2reservoirtarget: pd.Series
	zone: pd.Series
	zonecode: pd.Series