"""
This type stub file was generated by pyright.
"""

from contextlib import asynccontextmanager
from typing import AsyncIterator
from multilspy.language_server import LanguageServer

class DartLanguageServer(LanguageServer):
    """
    Provides Dart specific instantiation of the LanguageServer class. Contains various configurations and settings specific to Dart.
    """
    def __init__(self, config, logger, repository_root_path) -> None:
        """
        Creates a DartServer instance. This class is not meant to be instantiated directly. Use LanguageServer.create() instead.
        """
        ...
    
    def setup_runtime_dependencies(self, logger: MultilspyLogger) -> str:
        ...
    
    @asynccontextmanager
    async def start_server(self) -> AsyncIterator[DartLanguageServer]:
        """
        Start the language server and yield when the server is ready.
        """
        ...
    


