# coding: utf-8

"""
    Platform API

    _OpenAPI specification for the **Platform API** of **Empire**, the allocation and nomination platform of BritNed_  ---  Additional documentation available in the API's [GitHub repository](https://github.com/britned/empire-platform-api) 

    The version of the OpenAPI document: 6.1.0
    Contact: britned.info@britned.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from empire_platform_api_public_client_legacy.models.timescale_nomination_mtu_status import TimescaleNominationMtuStatus  # noqa: E501

class TestTimescaleNominationMtuStatus(unittest.TestCase):
    """TimescaleNominationMtuStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimescaleNominationMtuStatus(self):
        """Test TimescaleNominationMtuStatus"""
        # inst = TimescaleNominationMtuStatus()

if __name__ == '__main__':
    unittest.main()
