from . import pinocchio_pywrap as pin
from .deprecation import DeprecatedWarning as DeprecatedWarning, deprecated as deprecated
from .utils import npToTTuple as npToTTuple, npToTuple as npToTuple
from _typeshed import Incomplete

def impulseDynamics(model, data, *args): ...
def forwardDynamics(model, data, *args): ...
def jointJacobian(model, data, q, jointId): ...
def frameJacobian(model, data, q, frameId): ...
def computeCentroidalDynamics(model, data, q, v, a: Incomplete | None = None): ...

class GeometryObject(pin.GeometryObject):
    @property
    def fcl(self): ...

def se3ToXYZQUATtuple(M): ...
def se3ToXYZQUAT(M): ...
def XYZQUATToSe3(x): ...
def buildGeomFromUrdf(model, filename, *args, **kwargs): ...
def potentialEnergy(model, data, q, update_kinematics: bool = True): ...
def kineticEnergy(model, data, q, v, update_kinematics: bool = True): ...
def setGeometryMeshScales(geom_model, mesh_scale) -> None: ...
