import contextlib
from _typeshed import Incomplete

def get_dll_paths(): ...

class DllDirectoryManager(contextlib.AbstractContextManager):
    def add_dll_directory(self, dll_dir: str): ...
    dll_dirs: Incomplete
    def __enter__(self): ...
    def __exit__(self, *exc_details) -> None: ...

def build_directory_manager(): ...
