# coding: utf-8

"""
    Marketing i prodvihenie

    <div class=\"description_important\">       Uznat bolhe o marketinge i prodvihenii mohno v <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">spravohnom centre</a> </div>    Metody marketinga i prodvihenia pozvolaut:   1. Poluhat informaciu o [reklamnyh kampaniah](/openapi/promotion#tag/Kampanii) i [mediakampaniah](/openapi/promotion#tag/Media).   2. [Sozdavat](/openapi/promotion#tag/Sozdanie-kampanij) i [upravlat](/openapi/promotion#tag/Upravlenie-kampaniyami) kampaniami.   3. Nastraivat [parametry kampanii](/openapi/promotion#tag/Parametry-kampanij) — klastery fraz, prodvigaemye tovary i tak dalee.   4. Upravlat [finansami kampanii](/openapi/promotion#tag/Finansy).   5. Rabotat s [kalendarem akcii](/openapi/promotion#tag/Kalendar-akcij).  Dannye sinhroniziruutsa s bazoi raz v 3 minuty. Statusy kampanii menautsa raz v minutu. Stavki kampanii menautsa raz v 30 sekund.   # noqa: E501

    OpenAPI spec version: promotion
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponseInfoAdvertType8AutoParamsNmCPM(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nm': 'int',
        'cpm': 'int'
    }

    attribute_map = {
        'nm': 'nm',
        'cpm': 'cpm'
    }

    def __init__(self, nm=None, cpm=None):  # noqa: E501
        """ResponseInfoAdvertType8AutoParamsNmCPM - a model defined in Swagger"""  # noqa: E501
        self._nm = None
        self._cpm = None
        self.discriminator = None
        if nm is not None:
            self.nm = nm
        if cpm is not None:
            self.cpm = cpm

    @property
    def nm(self):
        """Gets the nm of this ResponseInfoAdvertType8AutoParamsNmCPM.  # noqa: E501

        Artikul WB  # noqa: E501

        :return: The nm of this ResponseInfoAdvertType8AutoParamsNmCPM.  # noqa: E501
        :rtype: int
        """
        return self._nm

    @nm.setter
    def nm(self, nm):
        """Sets the nm of this ResponseInfoAdvertType8AutoParamsNmCPM.

        Artikul WB  # noqa: E501

        :param nm: The nm of this ResponseInfoAdvertType8AutoParamsNmCPM.  # noqa: E501
        :type: int
        """

        self._nm = nm

    @property
    def cpm(self):
        """Gets the cpm of this ResponseInfoAdvertType8AutoParamsNmCPM.  # noqa: E501

        Stavka  # noqa: E501

        :return: The cpm of this ResponseInfoAdvertType8AutoParamsNmCPM.  # noqa: E501
        :rtype: int
        """
        return self._cpm

    @cpm.setter
    def cpm(self, cpm):
        """Sets the cpm of this ResponseInfoAdvertType8AutoParamsNmCPM.

        Stavka  # noqa: E501

        :param cpm: The cpm of this ResponseInfoAdvertType8AutoParamsNmCPM.  # noqa: E501
        :type: int
        """

        self._cpm = cpm

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponseInfoAdvertType8AutoParamsNmCPM, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseInfoAdvertType8AutoParamsNmCPM):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
