"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .paymentstatus import PaymentStatus
from .paymenttype import PaymentType
from .telecomoperator import TelecomOperator
from datetime import datetime
from nkwa_pay_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PaymentTypedDict(TypedDict):
    amount: NotRequired[int]
    created_at: NotRequired[datetime]
    currency: NotRequired[str]
    description: NotRequired[str]
    fee: NotRequired[int]
    id: NotRequired[str]
    merchant_id: NotRequired[int]
    payment_type: NotRequired[PaymentType]
    phone_number: NotRequired[str]
    status: NotRequired[PaymentStatus]
    telecom_operator: NotRequired[TelecomOperator]
    updated_at: NotRequired[datetime]


class Payment(BaseModel):
    amount: Optional[int] = None

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None

    currency: Optional[str] = None

    description: Optional[str] = None

    fee: Optional[int] = None

    id: Optional[str] = None

    merchant_id: Annotated[Optional[int], pydantic.Field(alias="merchantId")] = None

    payment_type: Annotated[
        Optional[PaymentType], pydantic.Field(alias="paymentType")
    ] = None

    phone_number: Annotated[Optional[str], pydantic.Field(alias="phoneNumber")] = None

    status: Optional[PaymentStatus] = None

    telecom_operator: Annotated[
        Optional[TelecomOperator], pydantic.Field(alias="telecomOperator")
    ] = None

    updated_at: Annotated[Optional[datetime], pydantic.Field(alias="updatedAt")] = None
