"""Adicionar coluna url à tabela images

Revision ID: 68b6373e8c4f
Revises: 48a47757e579
Create Date: 2025-03-26 01:25:20.423273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '68b6373e8c4f'
down_revision = '48a47757e579'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(length=255), nullable=True))
    op.add_column('images', sa.Column('image_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image_metadata')
    op.drop_column('images', 'url')
    # ### end Alembic commands ### 