# coding: utf-8

"""
    Tickforge API

    An API to interact with Uptick Internal Resources

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ServerTimezone(str, Enum):
    """
    Timezone tags
    """

    """
    allowed enum values
    """
    TZ_GB = 'tz_gb'
    TZ_AU = 'tz_au'
    TZ_WA = 'tz_wa'
    TZ_NZ = 'tz_nz'
    TZ_ET = 'tz_et'
    TZ_PT = 'tz_pt'
    TZ_CT = 'tz_ct'
    TZ_MT = 'tz_mt'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ServerTimezone from a JSON string"""
        return cls(json.loads(json_str))


