from _typeshed import Incomplete

class UefiBinary:
    KINDS: Incomplete
    guid: Incomplete
    def __init__(self, content: bytes | None, name: str | None, guid: str, ext: str | None) -> None: ...
    @property
    def content(self) -> bytes: ...
    @property
    def name(self) -> str: ...
    @property
    def ext(self) -> str: ...
    @property
    def is_ok(self) -> bool: ...

class UefiExtractor:
    FILE_TYPES: Incomplete
    SECTION_TYPES: Incomplete
    UI: Incomplete
    binaries: Incomplete
    def __init__(self, firmware_data: bytes, file_guids: list[str]) -> None: ...
    def extract_all(self, ignore_guid: bool = False) -> None: ...
