import rzpipe
from fwhunt_scan.uefi_protocols import UefiGuid as UefiGuid
from typing import Any

def get_int(item: str) -> int | None: ...
def get_xrefs_to_guids(rz: rzpipe.open, guids: list[UefiGuid]) -> list[int]: ...
def get_xrefs_to_data(rz: rzpipe.open, addr: int) -> list[int]: ...
def get_current_insn_index(insns: list[dict[str, Any]] | None, code_addr: int) -> int | None: ...
