import rzpipe
from _typeshed import Incomplete
from fwhunt_scan.uefi_protocols import UefiGuid as UefiGuid
from fwhunt_scan.uefi_types import ChildSwSmiHandler as ChildSwSmiHandler, SmiHandler as SmiHandler, SmiKind as SmiKind
from fwhunt_scan.uefi_utils import get_current_insn_index as get_current_insn_index, get_int as get_int, get_xrefs_to_data as get_xrefs_to_data, get_xrefs_to_guids as get_xrefs_to_guids
from typing import Any

SMI_KINDS: Incomplete

def get_interface_from_bb(insns: list[dict[str, Any]], code_addr: int) -> int | None: ...
def get_interface_global(insns: list[dict[str, Any]], code_addr: int) -> int | None: ...
def get_handler(insns: list[dict[str, Any]], kind: SmiKind) -> SmiHandler | None: ...
def get_handlers(rz: rzpipe.open, code_addr: int, interface: int, kind: SmiKind) -> list[SmiHandler]: ...
def get_smst_bb(insns: list[dict[str, Any]]) -> int | None: ...
def get_smst_func(rz: rzpipe.open, code_addr: int, interface: int) -> list[int]: ...
def get_smst_list(rz: rzpipe.open) -> list[int]: ...
def find_handler_register_service(insns: list[dict[str, Any]]) -> int | None: ...
def get_child_sw_smi_handler_bb(rz: rzpipe.open, insns: list[dict[str, Any]]) -> ChildSwSmiHandler | None: ...
def get_child_sw_smi_handlers(rz: rzpipe.open, smst_list: list[int]) -> list[ChildSwSmiHandler]: ...
def get_smi_handlers(rz: rzpipe.open) -> list[SmiHandler]: ...
