import multiprocessing
import multiprocessing.managers
from _typeshed import Incomplete
from playwright.sync_api import ConsoleMessage as ConsoleMessage, Page as Page

PLAYWRIGHT_DOWNLOAD_TIMEOUT: float
PLAYWRIGHT_START_TIMEOUT: float
WINDOW_SIZE_DEFAULT: Incomplete

def meshcat_recorder(meshcat_url: str, request_shm: multiprocessing.managers.ValueProxy, message_shm: multiprocessing.managers.ValueProxy) -> None: ...

class MeshcatRecorder:
    url: Incomplete
    is_open: bool
    is_recording: bool
    proc: multiprocessing.Process | None
    def __init__(self, url: str) -> None: ...
    def open(self) -> None: ...
    def __del__(self) -> None: ...
    def release(self) -> None: ...
    def capture_frame(self, width: int | None = None, height: int | None = None) -> str: ...
    def start_video_recording(self, fps: float, width: int, height: int) -> None: ...
    def add_video_frame(self) -> None: ...
    def stop_and_save_video(self, path: str) -> None: ...
