from .panda3d_visualizer import Panda3dApp as Panda3dApp
from _typeshed import Incomplete
from matplotlib.backends import qt_compat as qt_compat
from qt_compat import QtWidgets
from typing import Any

FRAMERATE: int

class Panda3dQWidget(Panda3dApp, QtWidgets.QWidget):
    paint_surface: Incomplete
    clock: Incomplete
    def __init__(self, parent: Any | None = None) -> None: ...
    def destroy(self) -> None: ...
    def close(self) -> bool: ...
    def paintEvent(self, event: Any) -> None: ...
    def resizeEvent(self, event: Any) -> None: ...
    def getMousePos(self) -> tuple[float, float]: ...
    def mousePressEvent(self, event: Any) -> None: ...
    def mouseReleaseEvent(self, event: Any) -> None: ...
    def wheelEvent(self, event: Any) -> None: ...
