# coding: utf-8

"""
    Wildberries cifrovoi

    Po voprosam raboty s WBD API, obrahaites v <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">tehniheskuu podderhku</a>.   # noqa: E501

    OpenAPI spec version: wbd
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KeysDeleteResponseStatuses(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'code': 'str',
        'message': 'str',
        'status': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'code': 'code',
        'message': 'message',
        'status': 'status'
    }

    def __init__(self, id=None, code=None, message=None, status=None):  # noqa: E501
        """KeysDeleteResponseStatuses - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._code = None
        self._message = None
        self._status = None
        self.discriminator = None
        self.id = id
        self.code = code
        self.message = message
        self.status = status

    @property
    def id(self):
        """Gets the id of this KeysDeleteResponseStatuses.  # noqa: E501

        Identifikator kluha  # noqa: E501

        :return: The id of this KeysDeleteResponseStatuses.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this KeysDeleteResponseStatuses.

        Identifikator kluha  # noqa: E501

        :param id: The id of this KeysDeleteResponseStatuses.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def code(self):
        """Gets the code of this KeysDeleteResponseStatuses.  # noqa: E501

        HTTP status-kod dla kahdoi operacii nad kluhom  # noqa: E501

        :return: The code of this KeysDeleteResponseStatuses.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this KeysDeleteResponseStatuses.

        HTTP status-kod dla kahdoi operacii nad kluhom  # noqa: E501

        :param code: The code of this KeysDeleteResponseStatuses.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self):
        """Gets the message of this KeysDeleteResponseStatuses.  # noqa: E501

        Opisanie k statusu udalenia  # noqa: E501

        :return: The message of this KeysDeleteResponseStatuses.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this KeysDeleteResponseStatuses.

        Opisanie k statusu udalenia  # noqa: E501

        :param message: The message of this KeysDeleteResponseStatuses.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def status(self):
        """Gets the status of this KeysDeleteResponseStatuses.  # noqa: E501

        Flag statusa udalenia (`true` - uspehno udalen, `false` - ohibka)  # noqa: E501

        :return: The status of this KeysDeleteResponseStatuses.  # noqa: E501
        :rtype: bool
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this KeysDeleteResponseStatuses.

        Flag statusa udalenia (`true` - uspehno udalen, `false` - ohibka)  # noqa: E501

        :param status: The status of this KeysDeleteResponseStatuses.  # noqa: E501
        :type: bool
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KeysDeleteResponseStatuses, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeysDeleteResponseStatuses):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
