def applyConfiguration(gui, name, tf) -> None: ...
def displayShape(gui, name, geom, color=(0.9, 0.9, 0.9, 1.0)): ...
def displayDistanceResult(gui, group_name, res, closest_points: bool = True, normal: bool = True) -> None: ...
def displayCollisionResult(gui, group_name, res, color=...) -> None: ...
