from .base_visualizer import BaseVisualizer
from _typeshed import Incomplete

__all__ = ['Panda3dVisualizer']

class Panda3dVisualizer(BaseVisualizer):
    visual_group: Incomplete
    collision_group: Incomplete
    display_visuals: bool
    display_collisions: bool
    viewer: Incomplete
    def initViewer(self, viewer: Incomplete | None = None, load_model: bool = False) -> None: ...
    def loadViewerModel(self, group_name, color: Incomplete | None = None) -> None: ...
    def getViewerNodeName(self, geometry_object, geometry_type): ...
    def display(self, q: Incomplete | None = None) -> None: ...
    def displayCollisions(self, visibility) -> None: ...
    def displayVisuals(self, visibility) -> None: ...
