from .robot_wrapper import RobotWrapper
from _typeshed import Incomplete

__all__ = ['RomeoWrapper']

class RomeoWrapper(RobotWrapper):
    q0: Incomplete
    opCorrespondances: Incomplete
    def __init__(self, filename, package_dirs: Incomplete | None = None, verbose: bool = False) -> None: ...
    def Mrh(self, q): ...
    def Jrh(self, q): ...
    def wJrh(self, q): ...
    def vrh(self, q, v): ...
    def Jlh(self, q): ...
    def Mlh(self, q): ...
    def Jlf(self, q): ...
    def Mlf(self, q): ...
    def Jrf(self, q): ...
    def Mrf(self, q): ...
