import numpy as np
import numpy.linalg as npl
from .pinocchio_pywrap.rpy import matrixToRpy as matrixToRpy, rotate as rotate, rpyToMatrix as rpyToMatrix

__all__ = ['np', 'npl', 'eye', 'zero', 'rand', 'isapprox', 'mprint', 'skew', 'cross', 'npToTTuple', 'npToTuple', 'rotate', 'rpyToMatrix', 'matrixToRpy', 'se3ToXYZQUAT', 'XYZQUATToSe3', 'fromListToVectorOfString']

def npToTTuple(M): ...
def npToTuple(M): ...
def eye(n): ...
def zero(n): ...
def rand(n): ...
def cross(a, b): ...
def skew(p): ...
def se3ToXYZQUAT(M): ...
def XYZQUATToSe3(vec): ...
def isapprox(a, b, epsilon: float = 1e-06): ...
def mprint(M, name: str = 'ans', eps: float = 1e-15): ...
def fromListToVectorOfString(items): ...
