# coding: utf-8

"""
    Zakazy DBS

    <div class=\"description_important\">       Uznat bolhe o zakazah DBS mohno v <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">spravohnom centre</a> </div>  Upravlenie [sborohnymi zadaniami](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) i [metadannymi](/openapi/orders-dbs#tag/Metadannye-DBS) zakazov DBS (Delivery by Seller).   # noqa: E501

    OpenAPI spec version: order
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrderNewDBSOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_b2b': 'bool'
    }

    attribute_map = {
        'is_b2b': 'isB2b'
    }

    def __init__(self, is_b2b=None):  # noqa: E501
        """OrderNewDBSOptions - a model defined in Swagger"""  # noqa: E501
        self._is_b2b = None
        self.discriminator = None
        if is_b2b is not None:
            self.is_b2b = is_b2b

    @property
    def is_b2b(self):
        """Gets the is_b2b of this OrderNewDBSOptions.  # noqa: E501

        Priznak B2B-prodahi:   - <code>false</code> — ne B2B-prodaha   - <code>true</code> — B2B-prodaha   # noqa: E501

        :return: The is_b2b of this OrderNewDBSOptions.  # noqa: E501
        :rtype: bool
        """
        return self._is_b2b

    @is_b2b.setter
    def is_b2b(self, is_b2b):
        """Sets the is_b2b of this OrderNewDBSOptions.

        Priznak B2B-prodahi:   - <code>false</code> — ne B2B-prodaha   - <code>true</code> — B2B-prodaha   # noqa: E501

        :param is_b2b: The is_b2b of this OrderNewDBSOptions.  # noqa: E501
        :type: bool
        """

        self._is_b2b = is_b2b

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderNewDBSOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderNewDBSOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
