UNION_SERVE_CONFIG_FILE_NAME: str = "union_serve_config.json"
UNION_SERVE_CONFIG_ENV_VAR: str = "UNION_SERVICE_CONFIG"
INTERNAL_APP_ENDPOINT_PATTERN_ENV_VAR: str = "INTERNAL_APP_ENDPOINT_PATTERN"
FILES_TAR_FILE_NAME = "include-files.tar.gz"
