# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .cloud_az_storage_blob_data_source import CloudAzStorageBlobDataSource
from .cloud_box_data_source import CloudBoxDataSource
from .cloud_confluence_data_source import CloudConfluenceDataSource
from .cloud_google_drive_data_source import CloudGoogleDriveDataSource
from .cloud_jira_data_source import CloudJiraDataSource
from .cloud_notion_page_data_source import CloudNotionPageDataSource
from .cloud_one_drive_data_source import CloudOneDriveDataSource
from .cloud_s_3_data_source import CloudS3DataSource
from .cloud_sharepoint_data_source import CloudSharepointDataSource
from .cloud_slack_data_source import CloudSlackDataSource


class PipelineDataSourceComponentOne_AzureStorageBlob(CloudAzStorageBlobDataSource):
    type: typing_extensions.Literal["AZURE_STORAGE_BLOB"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PipelineDataSourceComponentOne_Box(CloudBoxDataSource):
    type: typing_extensions.Literal["BOX"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PipelineDataSourceComponentOne_Confluence(CloudConfluenceDataSource):
    type: typing_extensions.Literal["CONFLUENCE"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PipelineDataSourceComponentOne_GoogleDrive(CloudGoogleDriveDataSource):
    type: typing_extensions.Literal["GOOGLE_DRIVE"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PipelineDataSourceComponentOne_Jira(CloudJiraDataSource):
    type: typing_extensions.Literal["JIRA"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PipelineDataSourceComponentOne_MicrosoftOnedrive(CloudOneDriveDataSource):
    type: typing_extensions.Literal["MICROSOFT_ONEDRIVE"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PipelineDataSourceComponentOne_MicrosoftSharepoint(CloudSharepointDataSource):
    type: typing_extensions.Literal["MICROSOFT_SHAREPOINT"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PipelineDataSourceComponentOne_NotionPage(CloudNotionPageDataSource):
    type: typing_extensions.Literal["NOTION_PAGE"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PipelineDataSourceComponentOne_S3(CloudS3DataSource):
    type: typing_extensions.Literal["S3"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PipelineDataSourceComponentOne_Slack(CloudSlackDataSource):
    type: typing_extensions.Literal["SLACK"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


PipelineDataSourceComponentOne = typing.Union[
    PipelineDataSourceComponentOne_AzureStorageBlob,
    PipelineDataSourceComponentOne_Box,
    PipelineDataSourceComponentOne_Confluence,
    PipelineDataSourceComponentOne_GoogleDrive,
    PipelineDataSourceComponentOne_Jira,
    PipelineDataSourceComponentOne_MicrosoftOnedrive,
    PipelineDataSourceComponentOne_MicrosoftSharepoint,
    PipelineDataSourceComponentOne_NotionPage,
    PipelineDataSourceComponentOne_S3,
    PipelineDataSourceComponentOne_Slack,
]
