categories = ["American Indian/Alaska Native Foods",
    "Bacon, Sausages & Ribs",
    "Baking Additives & Extracts",
    "Baking Decorations & Dessert Toppings",
    "Beef Products",
    "Bread",
    "Bread (Frozen)",
    "Broccoli",
    "Burgers",
    "Butter & Spread",
    "Canned Fish and Meat",
    "Canned Fruit",
    "Canned Meat",
    "Canned Seafood",
    "Canned Tuna",
    "Canned Vegetables",
    "Canned/Dried Veges",
    "Carrots",
    "Cereal",
    "Cereal Grains and Pasta",
    "Cheese",
    "Cheese/Cheese Substitutes",
    "Chocolate",
    "Coffee",
    "Coffee/Tea/Substitutes",
    "Cold cuts and cured meats",
    "Cooked & Prepared",
    "Cottage/ricotta cheese",
    "Crackers & Biscotti",
    "Cream",
    "Cream and cream substitutes",
    "Cream cheese, sour cream, whipped cream",
    "Cream/Cream Substitutes",
    "Croissants, Sweet Rolls, Muffins & Other Pastries",
    "Crusts & Dough",
    "Dairy and Egg Products",
    "Dried fruits",
    "Eggs & Egg Substitutes",
    "Energy, Protein & Muscle Recovery Drinks",
    "Finfish and Shellfish Products",
    "Fish",
    "Fish  Unprepared/Unprocessed",
    "Fish – Unprepared/Unprocessed",
    "Fish & Seafood",
    "Flavored milk, lowfat",
    "Flavored milk, reduced fat",
    "Flavored milk, whole",
    "Flours & Corn Meal",
    "Frozen Bread & Dough",
    "Frozen Breakfast Sandwiches, Biscuits & Meals",
    "Frozen Fish & Seafood",
    "Frozen Fruit & Fruit Juice Concentrates",
    "Frozen Vegetables",
    "Fruit & Vegetable Juice, Nectars & Fruit Drinks",
    "Fruit drinks",
    "Fruits and Fruit Juices",
    "Grains",
    "Grains/Cereal - Ready to Eat - (Shelf Stable)",
    "Grains/Flour",
    "Granulated, Brown & Powdered Sugar",
    "Herbal Supplements",
    "Herbs & Spices",
    "Honey",
    "Ice Cream & Frozen Yogurt",
    "Jam, Jelly & Fruit Spreads",
    "Ketchup, Mustard, BBQ & Cheese Sauce",
    "Legumes and Legume Products",
    "Meat mixed dishes",
    "Meat/Poultry/Other Animals  Prepared/Processed",
    "Meat/Poultry/Other Animals Sausages  Prepared/Processed",
    "Milk",
    "Milk, lowfat",
    "Milk, nonfat",
    "Non Alcoholic Beverages  Ready to Drink",
    "Non Alcoholic Beverages - Ready to Drink",
    "Nut & Seed Butters",
    "Nut and Seed Products",
    "Nuts and seeds",
    "Oatmeal",
    "Oils Edible",
    "Onions",
    "Other Condiments",
    "Other Drinks",
    "Other Grains & Seeds",
    "Other Meats",
    "Pasta by Shape & Type",
    "Pasta/Noodles",
    "Peaches and nectarines",
    "Pears",
    "Pepperoni, Salami & Cold Cuts",
    "Pickles, Olives, Peppers & Relishes",
    "Pineapple",
    "Popcorn, Peanuts, Seeds & Related Snacks",
    "Pork",
    "Pork Products",
    "Poultry Products",
    "Poultry, Chicken & Turkey",
    "Pre-Packaged Fruit & Vegetables",
    "Rice",
    "Salad Dressing & Mayonnaise",
    "Seasoning Mixes, Salts, Marinades & Tenderizers",
    "Shellfish Unprepared/Unprocessed",
    "Spices and Herbs",
    "Spices and Herbs",
    "Tomatoes",
    "Vegetable & Cooking Oils",
    "Vegetables and Vegetable Products",
    "Wholesome Snacks",
    "Yogurt"]