from mapafiscal.domain.common.perfil_contribuinte import PerfilContribuinte
from mapafiscal.domain.common.regime_tributacao import RegimeTributacao
from mapafiscal.domain.common.natureza_operacao import NaturezaOperacao
from mapafiscal.domain.common.finalidade import Finalidade
from mapafiscal.domain.common.tipo_incidencia import TipoIncidencia
from mapafiscal.domain.common.tipo_cliente import TipoCliente
from mapafiscal.domain.common.cst_icms import CST_ICMS
from mapafiscal.domain.common.cst_ipi import CST_IPI
from mapafiscal.domain.common.cst_pis_cofins import CST_PIS_COFINS
from mapafiscal.domain.common.uf import UF
from mapafiscal.domain.common.regime_especial import RegimeEspecial