# coding: utf-8

"""
    Platform API

    _OpenAPI specification for the **Platform API** of **Empire**, the allocation and nomination platform of BritNed_  ---  Additional documentation available in the API's [GitHub repository](https://github.com/britned/empire-platform-api) 

    The version of the OpenAPI document: 6.1.0
    Contact: britned.info@britned.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from empire_platform_api_public_client.models.invoice_summary import InvoiceSummary

class TestInvoiceSummary(unittest.TestCase):
    """InvoiceSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceSummary:
        """Test InvoiceSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceSummary`
        """
        model = InvoiceSummary()
        if include_optional:
            return InvoiceSummary(
                direction = 'GB_NL',
                net_amount = 1.337,
                net_amount_gbp = 1.337,
                vat_amount = 1.337,
                vat_amount_gbp = 1.337,
                exchange_rate = 1.337,
                exchange_rate_day = '2022-01-04'
            )
        else:
            return InvoiceSummary(
                direction = 'GB_NL',
                net_amount = 1.337,
                vat_amount = 1.337,
        )
        """

    def testInvoiceSummary(self):
        """Test InvoiceSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
