# coding: utf-8

"""
    Platform API

    _OpenAPI specification for the **Platform API** of **Empire**, the allocation and nomination platform of BritNed_  ---  Additional documentation available in the API's [GitHub repository](https://github.com/britned/empire-platform-api) 

    The version of the OpenAPI document: 6.1.0
    Contact: britned.info@britned.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from empire_platform_api_public_client.api.buy_now_offers_api import BuyNowOffersApi


class TestBuyNowOffersApi(unittest.TestCase):
    """BuyNowOffersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BuyNowOffersApi()

    def tearDown(self) -> None:
        pass

    def test_get_buy_now_offer_purchase_details(self) -> None:
        """Test case for get_buy_now_offer_purchase_details

        """
        pass

    def test_get_buy_now_offers(self) -> None:
        """Test case for get_buy_now_offers

        """
        pass

    def test_purchase_buy_now_offer(self) -> None:
        """Test case for purchase_buy_now_offer

        """
        pass


if __name__ == '__main__':
    unittest.main()
